import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, unlinkSync } from 'fs';

async function build() {
    // Step 1: 构建前端 JS bundle (IIFE, 所有 import/export → 闭包内)
    const frontendResult = await esbuild.build({
        entryPoints: ['src/frontend/app.js'],
        bundle: true,
        format: 'iife',
        target: 'es2020',
        write: false,
        minify: true,
    });
    const frontendJs = frontendResult.outputFiles[0].text;

    // Step 2: 读取 HTML 模板, 注入前端 JS
    let html = readFileSync('src/frontend/index.html', 'utf-8');
    html = html.replace('__FRONTEND_JS_PLACEHOLDER__', () => frontendJs);

    // Step 3: 生成 html-content.js (使用 JSON.stringify 安全嵌入, 避免逃逸链)
    const htmlModule = '// Auto-generated by build.js\nexport const HTML_CONTENT = ' + JSON.stringify(html) + ';\n';
    writeFileSync('src/build/html-content.js', htmlModule);

    // Step 4: 构建后端 bundle (包含 HTML_CONTENT)
    await esbuild.build({
        entryPoints: ['src/backend/index.js'],
        bundle: true,
        format: 'esm',
        target: 'es2022',
        outfile: 'dist/workers.js',
        external: ['cloudflare:*'],
        minify: true,
        drop: ['console'],
    });

    // Step 5: 清理生成的中间文件
    unlinkSync('src/build/html-content.js');

    // 输出文件大小
    const { statSync } = await import('fs');
    const size = statSync('dist/workers.js').size;
    console.log(`Build complete: dist/workers.js (${(size / 1024).toFixed(1)} KB)`);
}

build().catch(err => {
    console.error('Build failed:', err);
    process.exit(1);
});
